apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogspace-backend-deployment
  labels:
    app: blogspace-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogspace-backend
  template:
    metadata:
      labels:
        app: blogspace-backend
    spec:
      containers:
      - name: backend
        image: sreeharij/blogspace-backend:latest
        env: 
          - name: MONGO_DB_URI
            value: mongodb://blogspace-mongo:27017/blogspace
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
        
