apiVersion: v1
kind: Service
metadata:
  name: blogspace-backend-service
spec:
  type: ClusterIP
  selector:
    app: blogspace-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
