apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogspace-mongo
spec:
  selector:
    matchLabels:
      app: blogspace-mongo
  template:
    metadata:
      labels:
        app: blogspace-mongo
    spec:
      containers:
      - name: blogspace-mongo
        image: mongo:8.0
        ports:
        - containerPort: 27017
